const fs = require('fs');
let txt = fs.readFileSync('public/fluvia-en.js', 'utf8');

const dict = [
    // AUTH & LOGIN
    ["Bienvenido<br><em>de vuelta.</em>", "Welcome<br><em>back.</em>"],
    ["Crear<br><em>cuenta nueva.</em>", "Create<br><em>new account.</em>"],
    ["Registrarse", "Sign Up"],
    ["Ya tengo cuenta (Log In)", "Already have an account (Log In)"],
    ["Completa todos los campos", "Please fill in all fields"],
    ["Ingresando...", "Logging in..."],
    ["Registrando...", "Signing up..."],
    ["Registro exitoso. Inicia sesión para continuar.", "Registration successful. Please log in to continue."],
    ["Error de conexion", "Connection error"],
    ["Ingresa tu email arriba para recuperar la contraseña", "Enter your email above to recover your password"],
    ["Se ha enviado un enlace a tu correo.", "A recovery link has been sent to your email."],
    ["Error al enviar correo.", "Error sending email."],
    ["¿Olvidaste tu contraseña?", "Forgot your password?"],
    ["CONTRASENA", "PASSWORD"],
    
    // DASHBOARD
    ["Condiciones óptimas", "Optimal conditions"],
    ["Viento fuerte", "Strong wind"],
    ["Navegable — caudal ", "Navigable — flow "],
    ["bajo", "low"],
    ["registros · últimas 24h", "logs · last 24h"],
    ["no recent reading", "no recent reading"],
    ["Buenos dias,", "Good morning,"],
    ["Buenas tardes,", "Good afternoon,"],
    ["Buenas noches,", "Good evening,"],
    ["Capitan", "Captain"],
    ["FLOTA SINCRONIZADA", "FLEET SYNCHRONIZED"],
    ["Despejado", "Clear"],
    ["Mayormente despejado", "Mostly clear"],
    ["Parcialmente nublado", "Partly cloudy"],
    ["Nublado", "Cloudy"],
    ["Niebla", "Fog"],
    ["Llovizna", "Drizzle"],
    ["Lluvia", "Rain"],
    ["Chaparron", "Showers"],
    ["Tormenta", "Storm"],
    ["Variado", "Variable"],
    ["Exportando reporte del dashboard...", "Exporting dashboard report..."],
    ["cargas registradas", "refuels recorded"],
    ["tripulantes activos", "active crew"],
    ["disp. total", "total available"],
    ["embarcaciones", "vessels"],
    ["viajes total", "total trips"],
    ["Actividad", "Activity"],
    ["hace ", " "],
    ["Embarcacion", "Vessel"],
    ["ATENCIÓN", "ATTENTION"],
    ["EN PUERTO", "IN PORT"],
    ["En puerto", "In port"],
    ["en_puerto", "in_port"],
    ["en_viaje", "in_transit"],
    
    // FLEET PANEL
    ["Add Active", "Add Asset"],
    ["Total Actives", "Total Assets"],
    
    // MODAL FORMS
    ["New Solicitud de Viaje", "New Trip Request"],
    ["ORIGEN", "ORIGIN"],
    ["Puerto origen", "Origin port"],
    ["DESTINO", "DESTINATION"],
    ["Puerto destino", "Destination port"],
    ["CARGA (TON)", "CARGO (TON)"],
    ["FECHA SALIDA", "DEPARTURE DATE"],
    ["New Entrada de Bitacora", "New Logbook Entry"],
    ["TITULO", "TITLE"],
    ["Resumen", "Summary"],
    ["Embarcacion", "Vessel"],
    ["Observacion", "Observation"],
    ["Incidente", "Incident"],
    ["Maniobra", "Maneuver"],
    ["Navegacion", "Navigation"],
    ["DESCRIPCION", "DESCRIPTION"],
    ["Detalle...", "Details..."],
    ["Add Tripulante", "Add Crew Member"],
    ["NOMBRE", "NAME"],
    ["ROL", "ROLE"],
    ["Capitan", "Captain"],
    ["Timonel", "Helmsman"],
    ["Maquinista", "Engineer"],
    ["Marinero", "Seaman"],
    ["Cocinero", "Cook"],
    ["Asignar a...", "Assign to..."],
    ["DOCUMENTO", "DOCUMENT ID"],
    ["Nro documento", "Document number"],
    ["Registrar Fuel", "Record Fuel"],
    ["LITROS", "LITERS"],
    ["FECHA", "DATE"],
    ["New Orden de Maintenance", "New Maintenance Order"],
    ["Que reparar", "What to repair"],
    ["PRIORIDAD", "PRIORITY"],
    ["Alta", "High"],
    ["Media", "Medium"],
    ["Baja", "Low"],
    ["NOTAS", "NOTES"],
    ["Detalles...", "Details..."],
    ["REPUESTO", "SPARE PART"],
    ["Filtro de aceite", "Oil filter"],
    ["CATEGORIA", "CATEGORY"],
    ["Electrico", "Electric"],
    ["Hidraulico", "Hydraulic"],
    ["Casco", "Hull"],
    ["General", "General"],
    ["CANTIDAD", "QUANTITY"],
    ["STOCK MINIMO", "MIN STOCK"],
    ["Record Reading de Calado", "Record Draft Reading"],
    ["Nombre de la embarcacion", "Vessel name"],
    ["CALADO (METROS)", "DRAFT (METERS)"],
    ["CALADO MAXIMO (M)", "MAX DRAFT (M)"],
    ["OBSERVACIONES", "OBSERVATIONS"],
    ["Condiciones, ubicacion...", "Conditions, location..."],
    ["Report Incident", "Report Incident"],
    ["Descripcion breve del incidente", "Brief incident description"],
    ["Embarcacion afectada", "Affected vessel"],
    ["SEVERIDAD", "SEVERITY"],
    ["Critico", "Critical"],
    ["Alto", "High"],
    ["Medio", "Medium"],
    ["Bajo", "Low"],
    ["Colision", "Collision"],
    ["Encalladura", "Grounding"],
    ["Derrame", "Spill"],
    ["Averia mecanica", "Mechanical failure"],
    ["Incendio", "Fire"],
    ["Medico", "Medical"],
    ["Otro", "Other"],
    ["DESCRIPCION DETALLADA", "DETAILED DESCRIPTION"],
    ["Que ocurrio, donde, cuando, medidas tomadas...", "What happened, where, when, actions taken..."],
    
    // INVENTORY
    ["Repuesto", "Spare"],
    ["STOCK BAJO", "LOW STOCK"],
    [" uds", " units"],
    
    // CALADO
    ["CRITICO", "CRITICAL"],
    ["ALERTA", "ALERT"],
    ["OPTIMO", "OPTIMAL"],
    ["Desconocido", "Unknown"],
    ["Calado: ", "Draft: "],
    ["Lectura de calado: ", "Draft reading: "],
    ["Lectura", "Reading"],
    
    // INCIDENTS
    ["Abierto", "Open"],
    ["Incidente", "Incident"],
    
    // TRACKING
    ["EN TRANSITO", "IN TRANSIT"],
    ["en ruta", "en route"],
    ["completado", "completed"],
    ["No hay cargas en transito activo", "No active cargo in transit"],
    ["Origin", "Origin"],
    ["Destination", "Destination"],
    
    // REPORTS
    ["VESSELES", "VESSELS"],
    ["VIAJES TOTALES", "TOTAL TRIPS"],
    ["ENTRADAS BITACORA", "LOGBOOK ENTRIES"],
    ["Carga ", "Refuel "],
    ["Litros", "Liters"],
    ["Entradas", "Entries"],
    
    // ADMIN
    ["EMPRESAS", "COMPANIES"],
    ["USUARIOS", "USERS"],
    ["AIS ACTIVOS", "ACTIVE AIS"],
    ["basico", "basic"],
    ["barcos", "vessels"],
    ["Activa", "Active"],
    ["Inactiva", "Inactive"],
    ["Sin empresas", "No companies"],
    ["Sin nombre", "No name"],
    ["Sin asignar", "Unassigned"],
    ["Sin usuarios", "No users"],
    ["NOMBRE DE EMPRESA", "COMPANY NAME"],
    ["Ej: Naviera Guarani", "Ex: Guarani Shipping"],
    ["Crear Empresa", "Create Company"],
    ["Add User al Sistema", "Add System User"],
    ["Minimo 6 caracteres", "Minimum 6 characters"],
    ["NOMBRE COMPLETO", "FULL NAME"],
    ["Juan Perez", "John Doe"],
    ["EMPRESA", "COMPANY"],
    ["Operador", "Operator"],
    ["Visor", "Viewer"],
    ["Crear User", "Create User"],
    
    // COPILOT / AI
    ["Analizando datos...", "Analyzing data..."],
    ["Eres el AI Copilot de FluviaFleet, asistente maritimo-fluvial experto en la Paraguay-Parana Waterway. Responde en español, breve y profesional. Contexto de la empresa:", "You are the FluviaFleet AI Copilot, a maritime-fluvial expert assistant for the Paraguay-Parana Waterway. Respond in English, brief and professional. Company context:"],
    ["Pregunta del capitan: ", "Captain's question: "],
    ["No pude procesar la consulta.", "Could not process the query."],
    ["Error al conectar con el servidor IA.", "Error connecting to the AI server."],
    
    // PREDICTIVE MAINTENANCE
    ["Analizando...", "Analyzing..."],
    ["Gemini está analizando tu flota...", "Gemini is analyzing your fleet..."],
    ["No se encontraron predicciones.", "No predictions found."],
    ["Probabilidad: ", "Probability: "],
    [" días", " days"],
    
    // FUEL ANOMALIES
    ["Escaneando...", "Scanning..."],
    ["Auditando consumo de combustible...", "Auditing fuel consumption..."],
    ["Sin anomalías detectadas.", "No anomalies detected."],
    ["RIESGO ROBO", "THEFT RISK"],
    ["SOBRECONSUMO", "OVERCONSUMPTION"],
    ["PICO ANÓMALO", "ANOMALOUS SPIKE"],
    ["TENDENCIA", "TREND"],
    ["NORMAL", "NORMAL"],
    ["Desviación: ", "Deviation: "],
    
    // CONVOY
    ["Calculando...", "Calculating..."],
    ["Gemini está optimizando la formación...", "Gemini is optimizing the formation..."],
    ["Consumption estimado: ", "Estimated consumption: "],
    ["Proa:", "Bow:"],
    ["Fila 1:", "Row 1:"],
    ["Fila 2:", "Row 2:"],
    ["Popa:", "Stern:"],
    ["RIESGO", "RISK"],
    
    // DELETE
    ["Delete Registro", "Delete Record"],
    ["Seguro que queres eliminar?", "Are you sure you want to delete?"],
    ["Esta accion no se puede deshacer.", "This action cannot be undone."],
    ["Eliminando...", "Deleting..."],
    
    // PRICING
    ["Combo Flota", "Fleet Combo"],
    ["Facturacion ", "Billing "],
    ["mensual", "monthly"],
    ["anual", "yearly"],
    ["14 dias gratis", "14 days free"],
    ["Pago seguro via pasarela externa", "Secure payment via external gateway"],
    ["Al confirmar seras redirigido a la pasarela de pago segura para completar la transaccion.", "Upon confirmation you will be redirected to the secure payment gateway to complete the transaction."],
    ["Contratar ", "Subscribe "],
    ["Redirigiendo...", "Redirecting..."],
    ["Solicitud Enviada", "Request Sent"],
    ["Nuestro equipo se pondra en contacto para activar tu plan ", "Our team will contact you to activate your "],
    ["Recibirás un email con instrucciones de pago.", "You will receive an email with payment instructions."],
    ["Cerrar", "Close"],
    
    // MISC
    ["Gasoil", "Diesel"],
    ["pendiente", "pending"],
    ["Entrada", "Entry"],
    ["Tripulante", "Crew member"],
    ["Registro", "Record"],
    ["Orden", "Order"],
    ["Viaje", "Trip"],
    ["Trafico terceros", "Third-party traffic"],
    ["activos AIS", "active AIS"],
    ["activos", "active"],
    ["EMBARCADO", "ONBOARD"],
    [".toLocaleString('es',", ".toLocaleString('en',"],
    [".toLocaleDateString('es')", ".toLocaleDateString('en')"],
    [".toLocaleDateString('es',", ".toLocaleDateString('en',"],
    [".toLocaleTimeString('es',", ".toLocaleTimeString('en',"],
    ["INCIDENTE", "INCIDENT"],
    ["DEBUG - Respuesta IA inesperada (o vacía):", "DEBUG - Unexpected (or empty) AI response:"],
];

for (const [es, en] of dict) {
    txt = txt.split(es).join(en);
}

fs.writeFileSync('public/fluvia-en.js', txt);
console.log('Full JS translation complete. ' + dict.length + ' replacements applied.');